version: "3.8"

services:
  localstack:
    container_name: "local_aws"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
    environment:
      - SERVICES=sqs
      - DEBUG=${DEBUG-}
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1